CREATE PROCEDURE filtrar_Nombre (
	@InNombre VARCHAR(128) --PARAMETRO NOMBRE A FILTRAR
	,@InIp VARCHAR(64) --IP DEL USUARIO
	,@InUsuarios VARCHAR(16) --USERNAME QUE EJECUTO EL PROCEDIMIENTO
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT A.Nombre AS [Nombre] -- MUESTRA EL NOMBRE
		, C.Nombre AS [Clase Articulo] --MUESTRA EL NOMBRE DE CLASE DE ARTICULO
		, A.Precio AS [Precio] --MUESTRA EL PRECIO DEL ARTICULO
	
	FROM dbo.Articulo A --DE LA TABLA ARTICULOS
	INNER JOIN dbo.ClaseArticulo C ON A.IdClaseArticulo = C.id -- JUNTA LAS TABLAS Y REMPLAZA ID POR EL NOMBRE RELACIONADO DE LA CLASE ARTICULO
	WHERE A.Nombre LIKE '%'+@InNombre+'%' --SE BUSCA LOS NOMBRE QUE CONTENGAN LA COMBINACIÓN DEL PARAMETRO INTRODUCIDO
	ORDER BY A.Nombre ASC; --MUESTRA LA TABLA EN ORDEN ALFABETICO ASCENDENTE DEL NOMBRE
	 
	 EXEC dbo.Insertar_EventLog 'Consulta por Nombre', @InNombre, @InUsuarios, @InIp; --REGISTRA LA ACCIÓN REALIZADA CON LOS VALORES Y DATOS DE QUIEN LO HIZO EN EVENTLOG

	SET NOCOUNT OFF;--SE DESACTIVA SIEMPRE ANTES DE FINALIZAR.
END;