CREATE PROCEDURE Insertar_EventLog
(
	  @InAccion VARCHAR (64)
	, @InValor VARCHAR (256)
	, @InUsuarios VARCHAR (64)
	, @InIp VARCHAR(64)
)
As
BEGIN
	SET NOCOUNT ON; --ACTIVAR, PARA QUE NO ENVIE EL MENSAJE FILAS AFECTADAS
	
	DECLARE @Description VARCHAR(2000); -- SE DECLARA VARIABLE PARA FORMAR EL LOGDESCRIPTION 
	
	SET @Description = '<'+@InAccion+'> Description<'+@InValor+'>'; --SE FORMA EL LOGDESCRIPTION CON LOS PARAMETROS PASADOS
	
	INSERT INTO dbo.EventLog(LogDescription, PostIdUser, PostIP, PostTime) --SE INSERTAN LOS DATOS EN LA TABLA DE EVENTLOG
	VALUES 
	(
		@Description --VALOR DESCRIPCION
		,(SELECT id FROM dbo.Usuario A WHERE @InUsuarios = A.UserName) --SE CAMBIA EL NOMBRE DEL USUARIO POR EL ID EN TABLA DE USUARIOS
		, @InIp --IP DE LA COMPUTADORA
		, GETDATE() --FECHA DURANTE LA EJECUCIÓN DEL PROCEDURE.
	);

	SET NOCOUNT OFF;--SE DESACTIVA SIEMPRE ANTES DE FINALIZAR.
END