CREATE PROCEDURE listar_claseArticulos

AS
BEGIN
	SET NOCOUNT ON; --ACTIVAR, PARA QUE NO ENVIE EL MENSAJE DE FILAS AFECTADAS 

	SELECT A.Nombre --OBTIENE LOS NOMBRE DE LAS CLASES DE ARTICULOS
	FROM dbo.ClaseArticulo A --OBTIENE LOS VALORES DE LA TABLA CLASEARTICULOS
	ORDER BY A.Nombre ASC; --ORDENA LOS VALORES ALFABETICAMENTE
	
	SET NOCOUNT OFF; --SE DESACTIVA SIEMPRE AL FINALIZAR
END
EXEC dbo.listar_claseArticulos