ALTER PROCEDURE Filtrar_Cantidad
(
	@InCantidad INT --CANTIDAD DE ARTICULOS MOSTRADOS
	,@InIp VARCHAR(64)
	,@InUsuarios VARCHAR(16)
)
AS
BEGIN
	SET NOCOUNT ON; --ACTIVAR, PARA QUE NO ENVIE EL MENSAJE FILAS AFECTADAS
	
		SELECT TOP (@InCantidad) --MUESTRA LOS N ARTICULOS DADOS POR EL PARAMETRO 
			  A.Nombre AS [Nombre] -- MUESTRA EL NOMBRE
			, C.Nombre AS [Clase Articulo] --MUESTRA EL NOMBRE DE CLASE DE ARTICULO
			, A.Precio AS [Precio] --MUESTRA EL PRECIO DEL ARTICULO
		
		FROM dbo.Articulo A --DE LA TABLA ARTICULOS
		INNER JOIN dbo.ClaseArticulo C ON A.IdClaseArticulo = C.id -- JUNTA LAS TABLAS Y REMPLAZA ID POR EL NOMBRE RELACIONADO DE LA CLASE ARTICULO
		ORDER BY A.Nombre ASC; --MUESTRA LA TABLA EN ORDEN ALFABETICO ASCENDENTE DEL NOMBRE
		
		EXEC dbo.Insertar_EventLog 'Consulta por cantidad', @InCantidad, @InUsuarios, @InIp; --REGISTRA LA ACCIÓN REALIZADA CON LOS VALORES Y DATOS DE QUIEN LO HIZO EN EVENTLOG

	SET NOCOUNT OFF; --SE DESACTIVA SIEMPRE ANTES DE FINALIZAR.
END
